export const envUrl = {
  // baseUrl: 'http://192.168.0.144:8085/cyrusCMS/',
  //baseUrl: 'http://192.168.0.152:8085/cyrusCMS/',
  //baseUrl: 'http://192.168.0.135:8085/cyrusCMS/',
  //baseUrl: 'http://35.154.92.144:8085/cyrusCMS/',
  //baseUrl: 'http://35.154.92.144:8085/cyrusCMS/',
  // baseUrl: 'http://20.227.166.148:8085/cyrusCMS/',
  // baseUrl: 'http://192.168.0.134:8085/cyrusCMS/', //-----ishaan office ip -----//
  // baseUrl: 'http://192.168.29.229:8085/cyrusCMS/', //-----ishaan home ip -----//
  // baseUrl: 'http://192.168.0.181:8085/cyrusCMS/', //-----rajat office ip-----//
  baseUrl: 'https://node.sparkywarehouse.com.au/cyrusCMS/',
  // baseUrl: 'http://localhost:8085/cyrusCMS/',
  // baseUrl: 'https://local-sparky-node.loca.lt/cyrusCMS/', //-----local tunnel dev-----//
};
export const cmsendPoint = {
  login: 'login',
  getCategoryTable: 'getCategoryTable',
  getSubCategoryTable: 'getSubCategoryTable',
  getSubSubCategoryTable: 'getSubSubCategoryTable',
  //getCategorycms: 'getCategorycms',
  getCategoryRelatedData: 'getCategoryRelatedData',
  addCategory: 'addCategory',
  updateCategory: 'updateCategory',
  addSubSubCategory: 'addSubSubCategory',
  updateSubSubCategory: 'updateSubSubCategory',
  getProductRelatedData: 'getProductRelatedData',
  addProduct: 'addProduct',
  updateProduct: 'updateProduct',
  getProductTable: 'getProductTable',
  addMainBanner: 'addMainBanner',
  getMainBannerTable: 'getMainBannerTable',
  updateMainBanner: 'updateMainBanner',
  deleteBanner: 'deleteBanner',
  getBannerTable: 'getBannerTable',
  updateBanner: 'updateBanner',
  getContentTable: 'getContentTable',
  addContentData: 'addContentData',
  deleteContent: 'deleteContent',
  updateContent: 'updateContent',
  getFiltersAccordingToCategory: 'getFiltersAccordingToCategory',
  addFilterWithCategory: 'addFilterWithCategory',
  getSubCategoryTitleTable: 'getSubCategoryTitleTable',
  addSubcategoryTitle: 'addSubcategoryTitle',
  updateManageSubcategoryTitle: 'updateManageSubcategoryTitle',
  deleteSubcategoryTitle: 'deleteSubcategoryTitle',
  uploadStockExcel: 'uploadStockExcel',
  getstocktable: 'getstocktable',
  getOrdersList: 'getOrdersList',
  getUserTable: 'getUserTable',
  getOrderDetails: 'getOrderDetails',
  saveOrdersLogs: 'saveOrdersLogs',
  getOrderLogs: 'getOrderLogs',
  inactiveUser: 'inactiveUser',
  activeUser: 'activeUser',
  getexpotProductList: 'getexpotProductList',
  updateErpNumber: 'updateErpNumber',
  getexportOrderList: 'getexportOrderList',
  getProductDetailByID: 'getProductDetailByID',
  deleteProduct: 'deleteProduct',
  updateManageFilter: 'updateManageFilter',
  sendShippingEmail: 'sendShippingEmail',
  getCreditMembersList: 'getCreditMembersList',
  deleteSubCategory: 'deleteSubCategory',
  UpdateStatusCreditAccount: 'UpdateStatusCreditAccount',
  deleteCategory: 'deleteCategory',
  deleteFilter: 'deleteFilter',
  uploadImage: 'uploadImage',
  deleteUploadImage: 'deleteUploadImage',
  getIndustriesTable: 'getIndustriesTable',
  saveIndustry: 'saveIndustry',
  deleteIndustry: 'deleteIndustry',
  updateIndustry: 'updateIndustry',
  getBrandsTable: 'getBrandsTable',
  saveBrand: 'saveBrand',
  deleteBrand: 'deleteBrand',
  updateBrand: 'updateBrand',
  getCataloguesTable: 'getCataloguesTable',
  saveCatalogue: 'saveCatalogue',
  deleteCatalogue: 'deleteCatalogue',
  updateCatalogue: 'updateCatalogue',
  getCmsUserTable: 'getCmsUserTable',
  addCmsUser: 'addCmsUser',
  activeCmsUser: 'activeCmsUser',
  inactiveCmsUser: 'inactiveCmsUser',
  uploadCustPreAssembleData: 'uploadCustPreAssembleData',
  getCustPreassembleTable: 'getCustPreassembleTable',
  deleteCMSUser: 'deleteCMSUser',
  getQuotationsTable: 'getQuotationsTable',
  getQuoteData: 'getQuoteData',
  getAssemblySolutionsTable: 'getAssemblySolutionsTable',
  saveAssemblySolutions: 'saveAssemblySolutions',
  deleteAssemblySolutions: 'deleteAssemblySolutions',
  crudVoucher: 'crudVoucher',
  crudProductDiscount: 'crudProductDiscount',
  crudProductFilters: 'crudProductFilters',
  createOrderInTLM: 'createOrderInTLM',
  duplicateProduct: 'duplicateProduct',
  dashboardData: 'dashboardData',
  check: 'check',
};

export const HOME_PAGE = {
  SUPERADMIN: '/app/Dashboard',
  ADMIN: '/app/Dashboard',
};

export const COLOURS = {
  PRIMARY: '',
  SECONDARY: '',
  SUCCESS: '#2db77e',
  ERROR: '#e63635',
};
